### ISSUE TITLE
bsnes@115: The file 'C:\Users\user\scoop\apps\bsnes\115\settings.bml' already exists.

### ISSUE THREAD

**Issue by satorope** [borger/scoop-emulators#11]
Running pre-install script...
New-Item:
Line |
   2 |      New-Item "$dir\settings.bml" -Type File | Out-Null
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The file 'C:\Users\user\scoop\apps\bsnes\115\settings.bml' already exists.

**Comment by borger** [comment]
Hello @satorope , 

Can you please confirm if the issue persists?

Regards,

borger

**Comment by borger** [comment]
Closing as I did not hear back..
