### ISSUE TITLE
retroarch@1.9.11: Can't shim 'retroarch.exe': File doesn't exist.

### ISSUE THREAD

**Issue by satorope** [borger/scoop-emulators#12]
Installing 'retroarch' (1.9.11) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 0fc3f2|OK  |    10MiB/s|C:/Users/user/scoop/cache/retroarch#1.9.11#https_buildbot.libretro.com_stable_1.9.11_windows_x86_64_RetroArch.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of RetroArch.7z ... ok.
Extracting RetroArch.7z ... done.
Running pre-install script...
Linking ~\scoop\apps\retroarch\current => ~\scoop\apps\retroarch\1.9.11
Creating shim for 'retroarch'.
Can't shim 'retroarch.exe': File doesn't exist.

**Comment by borger** [comment]
This has been merged. Thank you for your contribution!
