### ISSUE TITLE
cemu@1.26.0c: hash check failed

### ISSUE THREAD

**Issue by coleth** [borger/scoop-emulators#15]
Checking hash of cemu_1.26.0.zip ... ERROR Hash check failed!
App:         emulators/cemu
URL:         http://cemu.info/releases/cemu_1.26.0.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    1783557ca60ae6b84cb114669ffb4f9b4db0ed1babc66bf1bacb15f2ce674fd6
Actual:      c5275a6ff31f4fa72ab45157156e2a74ed673156a57722ec32fb7278b0ac045c

**Comment by borger** [comment]
Hello @coleth , thank you for reporting, this has been fixed. can you please retry with the latest version (v1.26.1) ?

**Comment by coleth** [comment]
Yup, can confirm that 1.26.1 installs successfully.

**Comment by borger** [comment]
Thank you for confirming!
