### ISSUE TITLE
Needs some more emulators and love

### ISSUE THREAD

**Issue by beyondmeat** [borger/scoop-emulators#17]
Fix Retroarch, RPCS3, etc

Add:
- [x] BetterJoy
- [x] cxbx
- [x] ducksation-dev (nightly)
- [x] mame
- [x] mgba-dev (nightly)
- [x] redream
- [x] redream-dev (nightly)
- [x] retroarch-nightly
- [x] ryujinx
- [x] xemu
- [x] xenia
- [x] xenia-canary
- [x] fbneo
- [x] vita3k
- [x] yuzu-canary (Use pineapple-ea)

You don't seem to be actively maintaining this fork which is a bummer. Will you take PRs and merge them in? I see PRs sitting and don't want to waste my time contributing if you no longer have interest. This is one of the better ways to update standalone emus, so you should keep this going. @borger

**Comment by borger** [comment]
Hello @beyondmeat , absolutely! as you know its not easy to monitor all of the emulators by myself, download links change or become unavailable, anyway, any help is going to be appreciated, I will gladly accept PRs.

**Comment by beyondmeat** [comment]
https://github.com/Calinou/scoop-games/tree/master/bucket has most of these, I checked off which ones covered already. I might make my PRs to that repo since it seems like the main one now.

**Comment by beyondmeat** [comment]
i made prs to the repo i linked

**Comment by borger** [comment]
@beyondmeat do you mind if I port them over to this repo as well? I'd like to keep this as an emulator-only bucket...

**Comment by borger** [comment]
Thank you!

**Comment by beyondmeat** [comment]
fyi, i updated some of the manifests in scoop-games, some fixes since you pulled those in.

They also just setup free github actions to auto-update the manifests, might be a better approach that what you are doing.

**Comment by borger** [comment]
Hello @beyondmeat thank you for the update!

Yes, I do believe its a good idea to setup action to take care of the auto-update.. I'll look into it!

Also, your contributions have been many! Thank you! Feel free to use this repo and contribute as you have. Lots of gamers out there (me included) appreciate consolidating only emulators here. Let me know if you would like higher level access, to contribute further, you are most welcome.

**Comment by beyondmeat** [comment]
@borger I would like that, that way I can add any missing emus and perhaps setup the githubactions

**Comment by borger** [comment]
Cool, I've added you as a collaborator on the repo. Feel free to add your changes!

**Comment by borger** [comment]
Hello @beyondmeat , I forgot to mention that I added the Actions to auto-update, so far I left it hourly, but those development emulators do change a lot, in my auto-update setup before I had a bot that did it every 15 minutes. Let's see how the first few days, we can always change it if it doesn't work.

Another thing that I saw, is that some [AppVeyor](https://ci.appveyor.com/project/borger/scoop-emulators) are failing due to bizarre circumstances, can you help me sort those out? (check latest yuzu and ppsspp-dev builds for instance);
