### ISSUE TITLE
need more perms

### ISSUE THREAD

**Issue by beyondmeat** [borger/scoop-emulators#18]
want to drop appveyor for github actions, make issue,pr template, etc.

**Comment by borger** [comment]
Hello @beyondmeat,
I've added you as a collaborator, there's no additional permission I can give, you're basically an admin of the repo. Feel free to update appveyor/actions by editing their respective files in the repo and committing them. On the template side, if you can't do it via Settings, try creating the file manually e.g.: `.github/ISSUE_TEMPLATE/config.yml` that's how I created the auto-update actions. I suggest trying them on a branch first and then promoting them to `main`. Let me know if you need help setting it up.
