### ISSUE TITLE
[Bug]: RetroArch has incorrect hash

### ISSUE THREAD

**Issue by jewlexx** [borger/scoop-emulators#27]
### Prerequisites

- [X] I have ran `scoop update *` in powershell and verified the problem still exists.

### Emulator Name

RetroArch

### Error message or description of problem

The manifest for retroarch appears to have an incorrect hash. When downloading and getting hash via powershell normally, it returns `2FE124A9D58BC2D5260959B23574972478BFAD0D3C1FE10E9CEE63757642ABA6`, but the hash in the manifest is `5f51c57064e7dc221350fdff941f0335cc4fe44a7d2799d0fd8b7e907f3e6921`. The full error message is below.

```
ERROR Hash check failed!
App:         emulators/retroarch
URL:         https://buildbot.libretro.com/stable/1.14.0/windows/x86_64/RetroArch.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    5f51c57064e7dc221350fdff941f0335cc4fe44a7d2799d0fd8b7e907f3e6921
Actual:      2fe124a9d58bc2d5260959b23574972478bfad0d3c1fe10e9cee63757642aba6
```

**Comment by beyondmeat** [comment]
fixed
