### ISSUE TITLE
[Request]: shadPS4

### ISSUE THREAD

**Issue by tegaidogun** [borger/scoop-emulators#39]
### Prerequisites

- [X] I have searched all requests to ensure it has not already been requested.

### Criteria

- [] Reasonably well-known and widely used emulator
- [X] English interface
- [X] Emulator is actively developed and the latest release is less than 12 months old
- [X] Emulator is freeware or opensource. (No shareware or trialware)

### Name

shadPS4

### Description

A PS4 Emulator.

### Github or homepage

https://github.com/shadps4-emu/shadPS4

**Comment by beyondmeat** [comment]
Not at this time. It's broken and very early in development.

**Comment by beyondmeat** [comment]
This has been added
