### ISSUE TITLE
cemu@1.21.2: hash check failed

### ISSUE THREAD

**Issue by ejgomez** [borger/scoop-emulators#4]
App:         emulators/cemu
URL:         http://cemu.info/releases/cemu_1.21.2.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    f76cd97a94cb75fcb3bb641d35ea5ab463ce7ebf7d7ca07ac192fa13dd402cfb
Actual:      11b4d11fb0c0b13f96d5796bdf40975ff231d9cb57262fa8b1bef5d9dcda1e33

**Comment by borger** [comment]
Hello @ejgomez , I apologize for the delay in replying this is fixed now with the version 1.22.2. Feel free to open another Issue if you find errors again.
