### ISSUE TITLE
[Bug]: Dolphin-Beta not updating to 2407

### ISSUE THREAD

**Issue by tegaidogun** [borger/scoop-emulators#40]
### Prerequisites

- [X] I have ran `scoop update *` in powershell and verified the problem still exists.

### Emulator Name

Dolphin (Beta)

### Error message or description of problem

```console
The emulator recently changed the version control numbering system from stable releases to a full rolling release of (e.g from 5.0-21460 to 2407).

Albeit Dolphin - (Beta) here hasn't changed in GitHub.
```

**Comment by beyondmeat** [comment]
There is no more beta, switch to dolphin-dev if you want rolling releases.
